Add union validation utils (#2161)
This adds a `validateUnion` function, which can validate a union of
objects (with at least one common property), and throw readable errors
if validation fails.

For example, using the following structs:

```ts
const FooStruct = object({
  type: literal('a'),
  value: string(),
});

const BarStruct = object({
  type: literal('b'),
  value: number(),
});

const Union = union([FooStruct, BarStruct]);
```

We can use the `validateUnion` function with `type` as common property:

```ts
validateUnion(value, Union, 'type');
```

If the provided value does not have a valid type (i.e., it doesn't
satisfy any of the objects in the union), the function throws:

> Error: At path: type — Expected the value to be one of: "a", "b", but
received: "c".

If the type matches, but not the value (`{ type: 'b', value: 'foo' }`),
the function throws:

> Error: At path: value -- Expected a number, but received: "foo".